name: Reusable Terraform Workflow

on:
  workflow_call:
    inputs:
      terraform_version:
        required: true
        type: string

jobs:
  run-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Install Terraform
        run: |
          curl -O https://releases.hashicorp.com/terraform/${{ inputs.terraform_version }}/terraform_${{ inputs.terraform_version }}_linux_amd64.zip
          unzip terraform_${{ inputs.terraform_version }}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform -v
