name: Build & Push Docker Image 

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sivakalyan1998
          password: SIVAkalyan@1998
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: ./robot-shop/cart/
          push: true
          tags: sivakalyan1998/rrr:latest

