name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sivakalyan1998
          password: SIVAkalyan@1998
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: robot-shop/cart/Dockerfile
          push: true
          tags: sivakalyan1998/rrr:latest
