name: Install Terraform

on:
  workflow_dispatch:

jobs:
  install-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform v1.8.4
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      - name: Print Terraform version
        run: |
          echo "✅ Terraform has been installed successfully. Version is:"
          terraform -v
