name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker image
        run: |
          cd /cart/Dockerfile
          docker build -t ${{ secrets.DOCKER_USERNAME }}/Github_Actions:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/Github_Actions:latest
